# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
#- {name: 'Interesting Facts',  url: 'facts'}
#- {name: 'Learning Resources', url: 'resources'}
#- {name: 'Sample Posts',       url: 'sample-posts'}
- {name: 'Analytics',           url: 'documentation'}
- {name: 'About',              url: 'about'}
#- {name: 'Contact',            url: 'contact'}

dropdown_analyses:
- {name: 'Posts',       url: 'sample-posts'}
- {name: 'Covid-19',  url: 'facts'}
#- {name: 'Learning Resources', url: 'resources'}
#- {name: 'Analyses',           url: 'documentation'}
#- {name: 'About',              url: 'about'}
#- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link:    'https://twitter.com/paululele'}
#- {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
#- {icon: 'instagram', link:  'https://instagram.com/paululele'}
- {icon: 'github', link: 'https://github.com/KroghAnalytics'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/mortenpkrogh/'}
- {icon: 'envelope', link:   'mailto:kroghanalytics@gmail.com'}

#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}


sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
